curl --location --request POST 'https://dz-f10.cf69.com/f10/api/' \
--header 'Accept-Language: zh-CN' \
--header 'Org-key: dz' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Content-Type: application/json' \
--header 'Accept: */*' \
--header 'Host: dz-f10.cf69.com' \
--header 'Connection: keep-alive' \
--data-raw '{
  "trade_market": "SHMK",
  "mode_code": "2002",
  "body": {
    "stk_id": "600000",
    "fields": [
      "END_DATE",
      "INFO_PUB_DATE",
      "BEPS",
      "DEPS",
      "EPSED",
      "EPSNED",
      "BEPS_DED",
      "DEPS_DED",
      "EPSED_DED",
      "EPS_MOV",
      "EPS_TTM",
      "BPS",
      "BPSNED",
      "PS_OCF",
      "PER_OFW_TTM",
      "PS_TOR",
      "PS_OR",
      "PER_OPR_TTM",
      "PS_CR",
      "PS_SR",
      "PS_UP",
      "PS_RE",
      "PS_CN",
      "PER_CFW_TTM",
      "PS_EBIT",
      "PS_DIV",
      "ROEA",
      "ROEW",
      "ROED",
      "ROEA_DED",
      "ROEW_DED",
      "ROED_DED",
      "ROE_AIC",
      "FFD_ROE_12M",
      "FFD_ROEAPC_12M",
      "ROA",
      "ROA_NP",
      "ROIC",
      "ROE_YEAR",
      "ROA_YEAR",
      "ROA_NYEAR",
      "SAL_NPR",
      "SAL_GIR",
      "SAL_COST",
      "SAL_PFR",
      "TR_NP",
      "TR_OP",
      "TR_EBIT",
      "TR_TC",
      "TR_OF",
      "TR_MF",
      "TR_FF",
      "TR_AL",
      "ROE_PAR",
      "OP_ASS_RATIO",
      "OP_EQT_RATIO",
      "NON_RECR_FREQ",
      "SUSTAINABLE_GR",
      "DVD_COVER",
      "DVD_PAID_RATIO",
      "RET_EARN_RATIO",
      "CASH_DVD_COV",
      "HOLD_EQT_YOY",
      "TP_ONI",
      "TP_VCI",
      "TP_NON",
      "TP_TAX",
      "OR_SAL",
      "OR_OCF",
      "OR_ONI",
      "FCFF",
      "NET_CASH_FLOW",
      "CPT_REVN_RATIO",
      "ASS_DEBT",
      "EM",
      "TA_CA",
      "TA_NCA",
      "TA_TA",
      "TC_PCE",
      "TC_IBD",
      "TL_CL",
      "TL_NCL",
      "CR",
      "QR",
      "KQR",
      "ER",
      "TL_PCE",
      "IBD_PCE",
      "TL_TA",
      "IBD_TA",
      "ND_TA",
      "TL_OCF",
      "IBD_OCF",
      "CL_OCF",
      "ND_OCF",
      "IF_EBIT",
      "WK_LD",
      "OPE_CYC",
      "INV_DAYS",
      "ARC_DAYS",
      "INV_RATE",
      "ARC_RATE",
      "CA_RATE",
      "FA_RATE",
      "TA_RATE",
      "AP_RATE",
      "AP_DAYS",
      "EQT_TURN_RATIO",
      "BEPS_YOY",
      "DEPS_YOY",
      "PS_OCF_YOY",
      "TR_YOY",
      "OR_YOY",
      "OP_YOY",
      "TP_YOY",
      "PCNP_YOY",
      "PCNDP_YOY",
      "OCF_YOY",
      "ROE_YOY",
      "NP_YOY",
      "NET_CASH_FLOW_GR",
      "OP_PROFIT_GR",
      "FIN_NP_12MG",
      "FIN_OR_12MG",
      "FIN_OCE_12MG",
      "FIN_TOE_G",
      "BPS_YTD",
      "TA_YTD",
      "PCE_YTD",
      "EARNING_CHG",
      "CASH_FLOW_CHG_GR",
      "INC_A",
      "INC_B",
      "INC_C",
      "INC_D",
      "INC_E",
      "INC_F",
      "LOG_TOT_OP_REVENUE",
      "NET_NON_OP_INCOME",
      "NP_TP_RATIO",
      "NP_CUT_NP_RATIO",
      "NP_TTM_OR_RATIO",
      "NP_REVN_RATIO",
      "NP_CUT_REVN_RATIO",
      "EXTR_NP_RATIO",
      "GP_REVN_RATIO",
      "BAL_A",
      "BAL_B",
      "BAL_C",
      "BAL_D",
      "BAL_E",
      "BAL_F",
      "BAL_G",
      "BAL_H",
      "BAL_I",
      "TOT_ASS_LN",
      "RECV_PAY_RATIO",
      "CURT_DEBT_RATIO",
      "EQT_ASS_RATIO",
      "ITGB_ASS_RATIO",
      "DR",
      "OC_DEBT_RATIO",
      "OPER_CASH_ASS_RATIO"
    ],
    "max_date": "2000-01-01",
    "order_by_date": "asc",
    "page_num": 1,
    "page_size": 1
  }
}'