/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Arguments,
  Key
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  HTTPValidationError,
  SignInRequest,
  SignUpRequest
} from '.././models';



  
  
  
/**
 * @summary Signup
 */
export const signupApiAuthSignupPost = (
    signUpRequest: SignUpRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axios.post(
      `/api/auth/signup`,
      signUpRequest,options
    );
  }



export const getSignupApiAuthSignupPostMutationFetcher = ( options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: SignUpRequest }) => {
    return signupApiAuthSignupPost(arg, options);
  }
}
export const getSignupApiAuthSignupPostMutationKey = () => [`/api/auth/signup`] as const;

export type SignupApiAuthSignupPostMutationResult = NonNullable<Awaited<ReturnType<typeof signupApiAuthSignupPost>>>
export type SignupApiAuthSignupPostMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Signup
 */
export const useSignupApiAuthSignupPost = <TError = AxiosError<HTTPValidationError>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof signupApiAuthSignupPost>>, TError, Key, SignUpRequest, Awaited<ReturnType<typeof signupApiAuthSignupPost>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getSignupApiAuthSignupPostMutationKey();
  const swrFn = getSignupApiAuthSignupPostMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Signin
 */
export const signinUpass = (
    signInRequest: SignInRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axios.post(
      `/api/auth/signin/upass`,
      signInRequest,options
    );
  }



export const getSigninUpassMutationFetcher = ( options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: SignInRequest }) => {
    return signinUpass(arg, options);
  }
}
export const getSigninUpassMutationKey = () => [`/api/auth/signin/upass`] as const;

export type SigninUpassMutationResult = NonNullable<Awaited<ReturnType<typeof signinUpass>>>
export type SigninUpassMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Signin
 */
export const useSigninUpass = <TError = AxiosError<HTTPValidationError>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof signinUpass>>, TError, Key, SignInRequest, Awaited<ReturnType<typeof signinUpass>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getSigninUpassMutationKey();
  const swrFn = getSigninUpassMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Signout
 */
export const signout = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axios.post(
      `/api/auth/signout`,undefined,options
    );
  }



export const getSignoutMutationFetcher = ( options?: AxiosRequestConfig) => {
  return (_: Key, __: { arg: Arguments }) => {
    return signout(options);
  }
}
export const getSignoutMutationKey = () => [`/api/auth/signout`] as const;

export type SignoutMutationResult = NonNullable<Awaited<ReturnType<typeof signout>>>
export type SignoutMutationError = AxiosError<unknown>

/**
 * @summary Signout
 */
export const useSignout = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof signout>>, TError, Key, Arguments, Awaited<ReturnType<typeof signout>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getSignoutMutationKey();
  const swrFn = getSignoutMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
