/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Key
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  HTTPValidationError,
  SignInRequest,
  SignUpRequest
} from '.././models';



  
  
  
/**
 * @summary Signup
 */
export const signupApiAuthSignupPost = (
    signUpRequest: SignUpRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axios.post(
      `/api/auth/signup`,
      signUpRequest,options
    );
  }



export const getSignupApiAuthSignupPostMutationFetcher = ( options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: SignUpRequest }) => {
    return signupApiAuthSignupPost(arg, options);
  }
}
export const getSignupApiAuthSignupPostMutationKey = () => [`/api/auth/signup`] as const;

export type SignupApiAuthSignupPostMutationResult = NonNullable<Awaited<ReturnType<typeof signupApiAuthSignupPost>>>
export type SignupApiAuthSignupPostMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Signup
 */
export const useSignupApiAuthSignupPost = <TError = AxiosError<HTTPValidationError>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof signupApiAuthSignupPost>>, TError, Key, SignUpRequest, Awaited<ReturnType<typeof signupApiAuthSignupPost>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getSignupApiAuthSignupPostMutationKey();
  const swrFn = getSignupApiAuthSignupPostMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Signin
 */
export const signinApiAuthSigninUpassPost = (
    signInRequest: SignInRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axios.post(
      `/api/auth/signin/upass`,
      signInRequest,options
    );
  }



export const getSigninApiAuthSigninUpassPostMutationFetcher = ( options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: SignInRequest }) => {
    return signinApiAuthSigninUpassPost(arg, options);
  }
}
export const getSigninApiAuthSigninUpassPostMutationKey = () => [`/api/auth/signin/upass`] as const;

export type SigninApiAuthSigninUpassPostMutationResult = NonNullable<Awaited<ReturnType<typeof signinApiAuthSigninUpassPost>>>
export type SigninApiAuthSigninUpassPostMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Signin
 */
export const useSigninApiAuthSigninUpassPost = <TError = AxiosError<HTTPValidationError>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof signinApiAuthSigninUpassPost>>, TError, Key, SignInRequest, Awaited<ReturnType<typeof signinApiAuthSigninUpassPost>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getSigninApiAuthSigninUpassPostMutationKey();
  const swrFn = getSigninApiAuthSigninUpassPostMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
