/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Key
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  HTTPValidationError,
  SignInRequest,
  SignUpRequest
} from '.././models';



  
  
  
/**
 * @summary Signup
 */
export const signupAuthSignupPost = (
    signUpRequest: SignUpRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axios.post(
      `/auth/signup`,
      signUpRequest,options
    );
  }



export const getSignupAuthSignupPostMutationFetcher = ( options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: SignUpRequest }) => {
    return signupAuthSignupPost(arg, options);
  }
}
export const getSignupAuthSignupPostMutationKey = () => [`/auth/signup`] as const;

export type SignupAuthSignupPostMutationResult = NonNullable<Awaited<ReturnType<typeof signupAuthSignupPost>>>
export type SignupAuthSignupPostMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Signup
 */
export const useSignupAuthSignupPost = <TError = AxiosError<HTTPValidationError>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof signupAuthSignupPost>>, TError, Key, SignUpRequest, Awaited<ReturnType<typeof signupAuthSignupPost>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getSignupAuthSignupPostMutationKey();
  const swrFn = getSignupAuthSignupPostMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Signin
 */
export const signinAuthSigninUpassPost = (
    signInRequest: SignInRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axios.post(
      `/auth/signin/upass`,
      signInRequest,options
    );
  }



export const getSigninAuthSigninUpassPostMutationFetcher = ( options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: SignInRequest }) => {
    return signinAuthSigninUpassPost(arg, options);
  }
}
export const getSigninAuthSigninUpassPostMutationKey = () => [`/auth/signin/upass`] as const;

export type SigninAuthSigninUpassPostMutationResult = NonNullable<Awaited<ReturnType<typeof signinAuthSigninUpassPost>>>
export type SigninAuthSigninUpassPostMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Signin
 */
export const useSigninAuthSigninUpassPost = <TError = AxiosError<HTTPValidationError>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof signinAuthSigninUpassPost>>, TError, Key, SignInRequest, Awaited<ReturnType<typeof signinAuthSigninUpassPost>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getSigninAuthSigninUpassPostMutationKey();
  const swrFn = getSigninAuthSigninUpassPostMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
