/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  HTTPValidationError
} from '.././models';



  
  
  
/**
 * @summary Agui Proxy
 */
export const runAguiAgent = (
    path: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axios.post(
      `/api/agent/agui/${path}`,undefined,options
    );
  }



export const getRunAguiAgentMutationFetcher = (path: string, options?: AxiosRequestConfig) => {
  return (_: Key, __: { arg: Arguments }) => {
    return runAguiAgent(path, options);
  }
}
export const getRunAguiAgentMutationKey = (path: string,) => [`/api/agent/agui/${path}`] as const;

export type RunAguiAgentMutationResult = NonNullable<Awaited<ReturnType<typeof runAguiAgent>>>
export type RunAguiAgentMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Agui Proxy
 */
export const useRunAguiAgent = <TError = AxiosError<HTTPValidationError>>(
  path: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof runAguiAgent>>, TError, Key, Arguments, Awaited<ReturnType<typeof runAguiAgent>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getRunAguiAgentMutationKey(path);
  const swrFn = getRunAguiAgentMutationFetcher(path, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Status Proxy
 */
export const aguiStatus = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axios.get(
      `/api/agent/status`,options
    );
  }



export const getAguiStatusKey = () => [`/api/agent/status`] as const;

export type AguiStatusQueryResult = NonNullable<Awaited<ReturnType<typeof aguiStatus>>>
export type AguiStatusQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Status Proxy
 */
export const useAguiStatus = <TError = AxiosError<HTTPValidationError>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof aguiStatus>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getAguiStatusKey() : null);
  const swrFn = () => aguiStatus(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
