/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  HTTPValidationError
} from '.././models';



  
  
  
/**
 * @summary Agui Proxy
 */
export const aguiProxyApiAgentAguiPathPost = (
    path: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axios.post(
      `/api/agent/agui/${path}`,undefined,options
    );
  }



export const getAguiProxyApiAgentAguiPathPostMutationFetcher = (path: string, options?: AxiosRequestConfig) => {
  return (_: Key, __: { arg: Arguments }) => {
    return aguiProxyApiAgentAguiPathPost(path, options);
  }
}
export const getAguiProxyApiAgentAguiPathPostMutationKey = (path: string,) => [`/api/agent/agui/${path}`] as const;

export type AguiProxyApiAgentAguiPathPostMutationResult = NonNullable<Awaited<ReturnType<typeof aguiProxyApiAgentAguiPathPost>>>
export type AguiProxyApiAgentAguiPathPostMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Agui Proxy
 */
export const useAguiProxyApiAgentAguiPathPost = <TError = AxiosError<HTTPValidationError>>(
  path: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof aguiProxyApiAgentAguiPathPost>>, TError, Key, Arguments, Awaited<ReturnType<typeof aguiProxyApiAgentAguiPathPost>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getAguiProxyApiAgentAguiPathPostMutationKey(path);
  const swrFn = getAguiProxyApiAgentAguiPathPostMutationFetcher(path, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Status Proxy
 */
export const statusProxyApiAgentStatusGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axios.get(
      `/api/agent/status`,options
    );
  }



export const getStatusProxyApiAgentStatusGetKey = () => [`/api/agent/status`] as const;

export type StatusProxyApiAgentStatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof statusProxyApiAgentStatusGet>>>
export type StatusProxyApiAgentStatusGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Status Proxy
 */
export const useStatusProxyApiAgentStatusGet = <TError = AxiosError<HTTPValidationError>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof statusProxyApiAgentStatusGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getStatusProxyApiAgentStatusGetKey() : null);
  const swrFn = () => statusProxyApiAgentStatusGet(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
