/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  APIResponseCurrentUserResponseData
} from '.././models';



  
  
  
/**
 * Get current authenticated user information.

Returns:
  User information including id, username, and email
 * @summary Get Current User Info
 */
export const getCurrentUserInfoUserMeGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<APIResponseCurrentUserResponseData>> => {
    return axios.get(
      `/user/me`,options
    );
  }



export const getGetCurrentUserInfoUserMeGetKey = () => [`/user/me`] as const;

export type GetCurrentUserInfoUserMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUserInfoUserMeGet>>>
export type GetCurrentUserInfoUserMeGetQueryError = AxiosError<unknown>

/**
 * @summary Get Current User Info
 */
export const useGetCurrentUserInfoUserMeGet = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getCurrentUserInfoUserMeGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetCurrentUserInfoUserMeGetKey() : null);
  const swrFn = () => getCurrentUserInfoUserMeGet(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
