"""add salt

Revision ID: 031750940773
Revises: 154c0c1e749a
Create Date: 2025-11-03 11:32:34.147107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031750940773'
down_revision: Union[str, Sequence[str], None] = '154c0c1e749a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_password', sa.Column('salt', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_password', 'salt')
    # ### end Alembic commands ###
