"""<feat: company and report>

Revision ID: 8255322fb67c
Revises: 031750940773
Create Date: 2026-01-08 01:15:29.378087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8255322fb67c'
down_revision: Union[str, Sequence[str], None] = '031750940773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('china_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_code', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_china_company_company_code'), 'china_company', ['company_code'], unique=True)
    op.create_table('china_company_announcement_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('announcement_type', sa.String(length=50), nullable=False, comment='公告类型: Q1_REPORT, INTERIM_SUMMARY, INTERIM_REPORT, Q3_REPORT, ANNUAL_SUMMARY, ANNUAL_REPORT'),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('shareholders_equity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('report_status', sa.String(length=50), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['china_company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_china_company_announcement_file_announcement_type'), 'china_company_announcement_file', ['announcement_type'], unique=False)
    op.create_index(op.f('ix_china_company_announcement_file_company_id'), 'china_company_announcement_file', ['company_id'], unique=False)
    op.create_index(op.f('ix_china_company_announcement_file_report_year'), 'china_company_announcement_file', ['report_year'], unique=False)
    op.create_index('ix_company_year_type', 'china_company_announcement_file', ['company_id', 'report_year', 'announcement_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_company_year_type', table_name='china_company_announcement_file')
    op.drop_index(op.f('ix_china_company_announcement_file_report_year'), table_name='china_company_announcement_file')
    op.drop_index(op.f('ix_china_company_announcement_file_company_id'), table_name='china_company_announcement_file')
    op.drop_index(op.f('ix_china_company_announcement_file_announcement_type'), table_name='china_company_announcement_file')
    op.drop_table('china_company_announcement_file')
    op.drop_index(op.f('ix_china_company_company_code'), table_name='china_company')
    op.drop_table('china_company')
    # ### end Alembic commands ###
