/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ModelData } from './modelData';

export interface AgentData {
  name: string;
  model: ModelData;
  agent_id: string;
}
