/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { APIResponseGetSessionsResponseData } from './aPIResponseGetSessionsResponseData';

export interface APIResponseGetSessionsResponse {
  message?: string;
  code?: number;
  data?: APIResponseGetSessionsResponseData;
}
