/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CurrentUserResponseDataEmail } from './currentUserResponseDataEmail';

/**
 * Response model for current user information
 */
export interface CurrentUserResponseData {
  /** User ID */
  id: string;
  /** Username */
  username: string;
  /** User email address */
  email: CurrentUserResponseDataEmail;
}
