/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type GetCurrentUserSessionsParams = {
page_size?: number | null;
page_number?: number | null;
sort_order?: 'desc' | 'asc' | null;
};
