/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SessionData } from './sessionData';

export interface GetSessionsResponse {
  sessions: SessionData[];
  total: number;
  page_size: number;
  page_number: number;
}
