/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';



  
  
  
/**
 * @summary Health
 */
export const healthHealthGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axios.get(
      `/health`,options
    );
  }



export const getHealthHealthGetKey = () => [`/health`] as const;

export type HealthHealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthHealthGet>>>
export type HealthHealthGetQueryError = AxiosError<unknown>

/**
 * @summary Health
 */
export const useHealthHealthGet = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof healthHealthGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getHealthHealthGetKey() : null);
  const swrFn = () => healthHealthGet(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Root
 */
export const rootGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axios.get(
      `/`,options
    );
  }



export const getRootGetKey = () => [`/`] as const;

export type RootGetQueryResult = NonNullable<Awaited<ReturnType<typeof rootGet>>>
export type RootGetQueryError = AxiosError<unknown>

/**
 * @summary Root
 */
export const useRootGet = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof rootGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getRootGetKey() : null);
  const swrFn = () => rootGet(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Test1
 */
export const test1AFakeJsonStreamerGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axios.get(
      `/a_fake_json_streamer`,options
    );
  }



export const getTest1AFakeJsonStreamerGetKey = () => [`/a_fake_json_streamer`] as const;

export type Test1AFakeJsonStreamerGetQueryResult = NonNullable<Awaited<ReturnType<typeof test1AFakeJsonStreamerGet>>>
export type Test1AFakeJsonStreamerGetQueryError = AxiosError<unknown>

/**
 * @summary Test1
 */
export const useTest1AFakeJsonStreamerGet = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof test1AFakeJsonStreamerGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getTest1AFakeJsonStreamerGetKey() : null);
  const swrFn = () => test1AFakeJsonStreamerGet(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Test2
 */
export const test2AFakeJsonStreamerPost = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axios.post(
      `/a_fake_json_streamer`,undefined,options
    );
  }



export const getTest2AFakeJsonStreamerPostMutationFetcher = ( options?: AxiosRequestConfig) => {
  return (_: Key, __: { arg: Arguments }) => {
    return test2AFakeJsonStreamerPost(options);
  }
}
export const getTest2AFakeJsonStreamerPostMutationKey = () => [`/a_fake_json_streamer`] as const;

export type Test2AFakeJsonStreamerPostMutationResult = NonNullable<Awaited<ReturnType<typeof test2AFakeJsonStreamerPost>>>
export type Test2AFakeJsonStreamerPostMutationError = AxiosError<unknown>

/**
 * @summary Test2
 */
export const useTest2AFakeJsonStreamerPost = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof test2AFakeJsonStreamerPost>>, TError, Key, Arguments, Awaited<ReturnType<typeof test2AFakeJsonStreamerPost>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getTest2AFakeJsonStreamerPostMutationKey();
  const swrFn = getTest2AFakeJsonStreamerPostMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Test3
 */
export const test3FakeJsonStreamerGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axios.get(
      `/fake_json_streamer`,options
    );
  }



export const getTest3FakeJsonStreamerGetKey = () => [`/fake_json_streamer`] as const;

export type Test3FakeJsonStreamerGetQueryResult = NonNullable<Awaited<ReturnType<typeof test3FakeJsonStreamerGet>>>
export type Test3FakeJsonStreamerGetQueryError = AxiosError<unknown>

/**
 * @summary Test3
 */
export const useTest3FakeJsonStreamerGet = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof test3FakeJsonStreamerGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getTest3FakeJsonStreamerGetKey() : null);
  const swrFn = () => test3FakeJsonStreamerGet(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Test4
 */
export const test4FakeJsonStreamerPost = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axios.post(
      `/fake_json_streamer`,undefined,options
    );
  }



export const getTest4FakeJsonStreamerPostMutationFetcher = ( options?: AxiosRequestConfig) => {
  return (_: Key, __: { arg: Arguments }) => {
    return test4FakeJsonStreamerPost(options);
  }
}
export const getTest4FakeJsonStreamerPostMutationKey = () => [`/fake_json_streamer`] as const;

export type Test4FakeJsonStreamerPostMutationResult = NonNullable<Awaited<ReturnType<typeof test4FakeJsonStreamerPost>>>
export type Test4FakeJsonStreamerPostMutationError = AxiosError<unknown>

/**
 * @summary Test4
 */
export const useTest4FakeJsonStreamerPost = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof test4FakeJsonStreamerPost>>, TError, Key, Arguments, Awaited<ReturnType<typeof test4FakeJsonStreamerPost>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getTest4FakeJsonStreamerPostMutationKey();
  const swrFn = getTest4FakeJsonStreamerPostMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
