# The build context should be ./pnpm_packages/copilotkit-server
FROM node:20-alpine

WORKDIR /app
ENV NODE_ENV=production

RUN corepack enable
COPY ./package.json ./pnpm-lock.yaml ./

RUN id=pnpm-store,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile

COPY . .
RUN pnpm run build

RUN pnpm prune --prod

EXPOSE 6010
CMD ["node", "dist/index.js"]
