# The context should be the project root
FROM ghcr.io/astral-sh/uv:0.9.22-python3.12-trixie-slim

WORKDIR /app
COPY . .

# RUN uv sync --locked --package api
RUN uv sync --locked --package zhitou --no-group dev
RUN uv sync --locked --package zhitou_agent
RUN uv sync --locked --package api


ENTRYPOINT ["uv", "run", "api-dev"]